# Generated by Django 3.0.4 on 2020-03-11 19:36

from django.db import migrations, models
import what_cheer.models


class Migration(migrations.Migration):

    dependencies = [
        ('what_cheer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='image',
            field=models.ImageField(blank=True, upload_to=what_cheer.models.Entry.upload_image_name),
        ),
    ]
